# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.emacs.d/bin:$HOME/bin:$HOME/.bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# ZSH theme
ZSH_THEME="banana"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Compilation flags
export ARCHFLAGS="-arch x86_64"

## Clojure env vars
export LEIN_USERNAME=$USER
export LEIN_PASSWORD=""
export JVM_OPTS="-Dvlaaad.reveal.prefs={:theme,:dark,:font-family,\"Source Code Pro\",:font-size,14}"

## Put settings in here to avoid being loaded within emacs
if [[ -z $INSIDE_EMACS ]]; then
   plugins=(
      autoupdate
      git
      dnf
      zsh-256color
      zsh-autosuggestions
      fast-syntax-highlighting
      zsh-completions
      zsh-more-completions
      zsh-bash-completions-fallback
   )

   source $ZSH/oh-my-zsh.sh

   # ========================
   # auto generated by Zap AppImage Package Manager: do not remove!
   # Add the path to ZAP bin to PATH environment variable
   export ZAP_PATH=$HOME/.local/share/zap/bin
   export PATH=$PATH:$ZAP_PATH
   # ========================

   autoload -U compinit && compinit
fi

## Add settings for emacs - vterm
if [[ $INSIDE_EMACS = 'vterm' ]]; then
   alias clear='vterm_printf "51;Evterm-clear-scrollback";tput clear'
fi

## Add settings for SSH connections in here
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='emacs -nw'
fi

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
